name: car_pool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_map: ^5.0.0
  flutter_map_directions: ^0.0.5
  geocoding: ^3.0.0
  get: ^4.6.6
  iconsax_flutter: ^1.0.0
  latlong2: ^0.9.1
  twilio_flutter: ^0.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - assets/images/
